name: Update Resources
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  update-resources:
    if: ${{ github.repository_owner == 'pajlads' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Execute Resource Generator
        run: ./gradlew generateResources

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: "chore: update rarity data from ${{ steps.date.outputs.date }} wiki"
          commit-message: "chore: update rarity data from ${{ steps.date.outputs.date }} wiki"
          branch: automated/chore/update-resources
          reviewers: iProdigy
